---
# edit /etc/environment
- name: edit /etc/environment
  lineinfile:
    dest: /etc/environment
    regexp: "^(JAVA_HOME=)"
    state: present
    line: "JAVA_HOME={{ JAVA_HOME }}"


- name: add {{ JAVA_HOME }} to /etc/environmet
  replace:
    path: /etc/environment
    regexp: 'PATH=(["])((?!.*{{ JAVA_HOME }}).*)(["])'
    replace: 'PATH=\1\2:{{ (JAVA_HOME + "/bin") | replace("//","/") }}:\3'


- name: remove "::" from /etc/environmet
  replace:
    path: /etc/environment
    regexp: '::'
    replace: ":"