---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecle_java_test
    image: pycontribs/ubuntu
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
