---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Molecule Java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        # python-version: [3.6]

    steps:
      - name: check out
        uses: actions/checkout@v2
      

      - name: set up python3
        uses: actions/setup-python@v2
        # with:
          # python-version: ${{ matrix.python-version }}

      - name: install test depend
        run: pip3 install molecule docker
      
      - name: download java tar file
        run: wget https://iweb.dl.sourceforge.net/project/javajdk-8/JDK8/jdk-8u241-linux-x64.tar.gz -P /opt/
        # run: echo "balabala" > /opt/sample.txt ; tar czf jdk-8u241-linux-x64.tar.gz -C /opt/ sample.txt; mv jdk-8u241-linux-x64.tar.gz /opt

      - name: Run Molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLORE: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}